.\" 
.TH "pygame-salud" "29" "Jul 2009" "" "Games"
.SH "NAME"
pygame\-salud \- Set of kids games developed using Python
.SH "SYNOPSIS"
.B pygame\-salud
.SH "DESCRIPTION"
Pygame-salud is a set of kids games and educational software
developed using Python. Between the games we have: word search puzzle, 
crazy letters, puzzle, links the parts.

.SH "SEE ALSO"
The source code for the script is at /usr/share/games/pygame-salud.

You can find more information at http://proyectos.canaima.softwarelibre.gob.ve/actividades-salud
