.\" 
.TH "pygame-salud" "29" "Jul 2009" "" "Games"
.SH "NAME"
pygame\-salud \- Bla
.SH "SYNOPSIS"
.B pygame\-salud
.SH "DESCRIPTION"
Bla Bla

.SH "SEE ALSO"
The source code for the script is at /usr/share/games/pygame-salud.

You can find more information at http://proyectos.canaima.softwarelibre.gob.ve/actividades-salud
